CREATE TABLE [dbo].[LikedDogs]
(
    [User_ID1] UNIQUEIDENTIFIER NOT NULL, 
    [Dog_ID2] UNIQUEIDENTIFIER NOT NULL, 
	CONSTRAINT [FK_ID1] FOREIGN KEY ([User_ID1]) REFERENCES [User]([Id]),
	CONSTRAINT [FK_ID2] FOREIGN KEY ([Dog_ID2]) REFERENCES [Dog]([Id]),
	PRIMARY KEY ([User_ID1], [Dog_ID2])
)

